environment:
  matrix:
  - nodejs_version: "10"
  - nodejs_version: "13"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build: off
shallow_clone: true
test_script:
  - node --version
  - npm --version
  - npm test
