minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@types/node@26.5.1'

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 604800 # 7 days

update:
  ignoreDeps:
    - typescript@7

shellEmulator: true
